- title: Do large language models solve ARC visual analogies like people do?
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=aGQaCEcAAAAJ&citation_for_view=aGQaCEcAAAAJ:u5HHmVD_uO8C
  citation_id: aGQaCEcAAAAJ:u5HHmVD_uO8C
  authors: G Opiełka, H Rosenbusch, V Vijverberg, CE Stevenson
  publication: Annual Meeting of the Cognitive Science Society (CogSci 2024), 2024
  cited_by:
    value: 3
    link: https://scholar.google.com/scholar?oi=bibs&hl=en&cites=942169884171881483
    serpapi_link: https://serpapi.com/search.json?cites=942169884171881483&engine=google_scholar&hl=en
    cites_id: '942169884171881483'
  year: '2024'

- title: Analogical Reasoning Inside Large Language Models: Concept Vectors and the Limits of Abstraction
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=aGQaCEcAAAAJ&citation_for_view=aGQaCEcAAAAJ:d1gkVwhDpl0C
  citation_id: aGQaCEcAAAAJ:d1gkVwhDpl0C
  authors: G Opiełka, H Rosenbusch, CE Stevenson
  publication: arXiv preprint arXiv:2503.03666, 2025
  cited_by:
    value: null
  year: '2025'

- title: Saliency Suppressed, Semantics Surfaced: Visual Transformations in Neural Networks and the Brain
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=aGQaCEcAAAAJ&citation_for_view=aGQaCEcAAAAJ:u-x6o8ySG0sC
  citation_id: aGQaCEcAAAAJ:u-x6o8ySG0sC
  authors: G Opiełka, J Loke, S Scholte
  publication: ICLR 2024 Re-Align Workshop, 2024
  cited_by:
    value: null
  year: '2024'
