- title: Network models for cognitive development and intelligence
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=nmT-EaUAAAAJ&pagesize=100&citation_for_view=nmT-EaUAAAAJ:LPtt_HFRSbwC
  citation_id: nmT-EaUAAAAJ:LPtt_HFRSbwC
  authors: HLJ Van Der Maas, KJ Kan, M Marsman, CE Stevenson
  publication: Journal of Intelligence 5 (2), 16, 2017
  cited_by:
    value: 193
    link: https://scholar.google.com/scholar?oi=bibs&hl=en&cites=9931121143319529214
    serpapi_link: https://serpapi.com/search.json?cites=9931121143319529214&engine=google_scholar&hl=en
    cites_id: '9931121143319529214'
  year: '2017'
